name: Delete Old Workflow Run
on:
  workflow_dispatch:
    inputs:
      purge_workflow:
        description: 'Purge Workflow: Select which workflow runs to purge.'
        required: true
        default: publish-drafts.yml
        type: choice
        options:
          - publish-drafts.yml
          - publish-jekyll-site-to-github-pages.yml
          - delete-old-workflow-runs.yml
      dry_run:
        description: 'DryRun: If true, only log actions, otherwise perform purge.'
        required: true
        default: true

jobs:
  purge_workflow_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Publish Draft Workflow Runs
        if: ${{ inputs.purge_workflow == 'publish-drafts.yml'
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 14
          keep_minimum_runs: 10
          delete_workflow_pattern: publish-drafts.yml
          delete_workflow_by_state_pattern: All
          dry_run: ${{ inputs.dry_run }}