name: Publish Dave's Technical Journal

on:
  # run when a commit is pushed to main, typically when a post is published
  push:
    branches:
      - main
    paths:
      - '_posts/**'
      - 'assets/images/**'

  # run when a pull request is merged, typically when a post is published or a draft is renamed
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - '_posts/**'
      - 'assets/images/**'

  # run on demand
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    if: |
      (github.event.push && contains(github.event.head_commit.message, 'publish')) ||
      github.event.pull_request.merged == true ||
      github.event_name == 'workflow_dispatch'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3.0.5
        with:
          generator_config_file: _config.yml

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1.0.7
        with:
          source: ./
          destination: ./_site
          verbose: false

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1.0.8

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.0
