name: Purge Workflow Runs

on:
  schedule:
    - cron: '0 16 * * *'

  workflow_dispatch:

jobs:
  purge_workflow_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Purge Workflow Runs for Rename Draft Articles Workflow
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 14
          keep_minimum_runs: 10
          delete_workflow_pattern: draft

      - name: Purge Workflow Runs for Publish Jekyll Site to GH Pages
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 60
          keep_minimum_runs: 15
          delete_workflow_pattern: publish

      - name: Purge Workflow Runs for Skipped Workflows
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 5
          delete_run_by_conclusion_pattern: skipped

      - name: Purge Workflow Runs for Failed Workflows
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 5
          delete_run_by_conclusion_pattern: failure

      - name: Purge Workflow Runs for Self
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 5
          delete_workflow_pattern: purge
