name: Rename Draft Articles

on:
  # schedule:
    # every 4 hours on the half hour
    # - cron: '30 */4 * * *'
    # every hour at 5 minutes past the hour
    # - cron: '05 * * * *'
  # on demand
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: PowerShell Module Cache
      uses: potatoqualitee/psmodulecache@v4.5
      with:
        modules-to-cache: powershell-yaml

    - name: Rename Draft Articles
      run: |
        sudo timedatectl set-timezone 'America/Chicago'
        Set-Location -Path $env:GITHUB_WORKSPACE
        ./script/Rename-DraftArticle.ps1

    # - name: Jekyll Publish Drafts
    #   uses: soywiz/github-action-jekyll-publish-drafts@v2
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     jekyll_path: ./
    #     branch: main
